### ISSUE TITLE
Τα Templates λειτουργούν μόνο με το theme του επινοώ 

### ISSUE THREAD

**Issue by johnnyxid** [eellak/facebook-cbp-app#1]
Τα Templates λειτουργούν μόνο με το wordpress theme του επινοώ, εάν αλλαχθεί το theme βγάζει σφάλμα και δεν λειτουργεί η σελίδα. θα πρέπει να τροποποιηθούν τα αρχεία ώστε να λειτουργούν με όλα ή τα περισσότερα themes.

Η οδηγία #6 του installation λειτουργεί μόνο με το συγκεκριμένο theme. η συγκεκριμένη λειτουργικότητα δεν υπάρχει στα άλλα themes

**Comment by gmetal** [comment]
Τα templates έγιναν theme-specific, και από τη φύση τους, αλλά και για να δένουν καλύτερα με το υπόλοιπο site.. Στο τελευταίο commit (c99b65ff) αλλάχτηκαν ώστε να είναι theme-agnostic. Κατά πάσα πιθανότητα, κάποια πράγματα θα θέλουν μερικές διορθώσεις ώστε να φαίνονται καλύτερα στον χρήστη.

Η οδηγία #6 αναφέρεται στην εγκατάσταση του plugin στον φάκελο με τα plugins του wordpress. Δεν καταλαβαίνω γιατί είναι theme specific. 

Εννοείς το:
6. Install the epinoo-fb-map plugin, by copying the epinoo-fb-map folder to the wordpress plugins folder
